### ISSUE TITLE
Has this FuzzBuilderEx paper been published yet?

### ISSUE THREAD

**Issue by SmllXzBZ** [kppw99/FuzzBuilderEx#7]
Hello, I am very interested in this project.
I would like to ask whether the paper of the project has been published, is there any full text available for reading?

**Comment by kppw99** [comment]
I appreciate your interest. FuzzBuilderEx paper is still under review in Journal. When it is published, I will notify reference information at GitHub.

**Comment by SmllXzBZ** [comment]
thank you
