### ISSUE TITLE
./fuzzbuilderex

### ISSUE THREAD

**Issue by Xandra298** [kppw99/FuzzBuilderEx#9]
where is ./fuzzbuilderex? After docker build,I can't find out how to use the" ./fuzzbuilderex seed "and so on.

**Comment by onsoim** [comment]
First of all, I apologize for the delay in responding.

You asked where is the fuzzbuilderex binary and how to use it.
For the consistency with previous research, it is still named "fuzzbuilder" not "fuzzbuilderex".

The location of the fuzzbuilder binary is `/tool/fuzzbuiler` and the example usage of it is `/tool/fuzzbuilder seed /exp/boringssl/seed.conf`.
You could get more hints from https://github.com/kppw99/FuzzBuilderEx/blob/main/projects/boringssl/Dockerfile#L20. 

If you have any further questions, please ease to ask them again. THX

**Comment by Xandra298** [comment]
I see. Thanks for the reply!
